# lan trunk out traffic
{
  systemd.network.networks."20-lan-primary" = {
    matchConfig.Name = "eno3";
    networkConfig = {
      # debug
      DHCP = "ipv4";

      #Bridge = "br-lan";
      #IPv6AcceptRA = true;
      IPv4Forwarding = true;
    };
    #linkConfig.RequiredForOnline = "routable";
    dhcpV4Config = {
      UseDNS = false;
      UseRoutes = true;
      UseGateway = false;
    };
  };

  # boot.kernel.sysctl = { "net.ipv4.conf.all.rp_filter" = 0; };
  # systemd.network.links."eno1".enable = false;
  # systemd.network.networks."10-lan-secondary" = {
  #   matchConfig.Name = "eno1";
  #   networkConfig.DHCP = "ipv4";
  #   dhcpV4Config = {
  #     #There are multiple network interfaces on the machine connected to the same local area network.
  #     #The primary interface has already applied the network configuration obtained from DHCP server,
  #     #so we do not want this interface to obtain the same configuration again.
  #     UseDNS = false;
  #     SendHostname = false;
  #     #disable default routes.
  #     # N.B Even if DHCP routing is disabled, the system may still automatically generate a local subnet route
  #     # based on the subnet mask of the IP address, for example:
  #     # * If the network interface obtains the address 192.168.1.100/24, the system will automatically
  #     # add a route for 192.168.1.0/24.
  #     # * This route is automatically generated by the kernel (unrelated to DHCP) and cannot be directly
  #     # disabled through systemd-networkd configuration.
  #     UseRoutes = false;
  #   };
  # };

}
